### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by eileenfan** [ppareit/swiftp#110]
//package name: be.ppareit.swiftp
//version: 2.13.1
 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SEND typ=message/rfc822 flg=0x1 (has clip) (has extras) }
 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
 	at android.app.Activity.startActivityForResult(Activity.java:3390)
 	at android.app.Activity.startActivityForResult(Activity.java:3351)
 	at android.app.Activity.startActivity(Activity.java:3587)
 	at android.app.Activity.startActivity(Activity.java:3555)
 	at be.ppareit.swiftp.gui.FsPreferenceActivity.onOptionsItemSelected(FsPreferenceActivity.java:289)
 	at android.app.Activity.onMenuItemSelected(Activity.java:2566)
 	at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:986)
 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:742)
 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:881)
 	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:156)
 	at android.widget.AdapterView.performItemClick(AdapterView.java:298)
 	at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
 	at android.widget.AbsListView.onKeyUp(AbsListView.java:2929)
 	at android.widget.ListView.commonKey(ListView.java:2267)
 	at android.widget.ListView.onKeyUp(ListView.java:2122)
 	at android.view.KeyEvent.dispatch(KeyEvent.java:2647)
 	at android.view.View.dispatchKeyEvent(View.java:7343)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1388)
 	at android.widget.ListView.dispatchKeyEvent(ListView.java:2097)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.widget.PopupWindow$PopupViewContainer.dispatchKeyEvent(PopupWindow.java:1583)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3791)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3774)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)

**Comment by ppareit** [comment]
Must be that there is no application that can handle the ACTION_SEND
(email for instance) available. We will handle this case gracefully in
the next update. Thanks for the report!

eileenfan schreef op ma 11-09-2017 om 05:11 [+0000]:
