### ISSUE TITLE
FATAL EXCEPTION: Unable to start receiver be.ppareit.swiftp.gui.FsWidgetProvider

### ISSUE THREAD

**Issue by WangGuox1n** [ppareit/swiftp#140]
Hi, I developed an automatic-testing tool and it detected an exception in your app(version 2.19).
I would like to know if you consider it as a bug?

**STACK_TRACE**=E/AndroidRuntime( 1876): FATAL EXCEPTION: main
E/AndroidRuntime( 1876): Process: be.ppareit.swiftp, PID: 1876
E/AndroidRuntime( 1876): java.lang.RuntimeException: Unable to start receiver be.ppareit.swiftp.gui.FsWidgetProvider: java.lang.NullPointerException
E/AndroidRuntime( 1876): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2414)
E/AndroidRuntime( 1876): 	at android.app.ActivityThread.access$1700(ActivityThread.java:135)
E/AndroidRuntime( 1876): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
E/AndroidRuntime( 1876): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1876): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 1876): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 1876): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1876): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1876): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 1876): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 1876): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1876): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1876): 	at be.ppareit.swiftp.gui.FsWidgetProvider.onReceive(FsWidgetProvider.java:53)
E/AndroidRuntime( 1876): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2407)
E/AndroidRuntime( 1876): 	... 10 more

**Comment by ppareit** [comment]
This is probably when intent.getAction() returns null. This receiver should not be called without an action. But it is still a case that should be handled.
