### ISSUE TITLE
window leak in ManagerUsersActivity

### ISSUE THREAD

**Issue by anlalalu** [ppareit/swiftp#150]
###### Reproduction Steps

1. tap 'Manage users'
2. tap 'add user'
3. tap 'select documents' and a dialog appears
4. rotate the screen

###### Expected Result

The dialog still exist without any error log.

###### Actual Result

The dialog disappears with the stack trace:

E/WindowManager: android.view.WindowLeaked: Activity be.ppareit.swiftp.gui.ManageUsersActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{528ecbb4 V.E..... R....... 0,0-729,1134} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                    at android.app.Dialog.show(Dialog.java:286)
                                                    at be.ppareit.swiftp.gui.UserEditFragment.showFolderPicker(UserEditFragment.java:94)
                                                    at be.ppareit.swiftp.gui.UserEditFragment.lambda$onCreateView$1(UserEditFragment.java:50)
                                                    at be.ppareit.swiftp.gui.-$$Lambda$UserEditFragment$QQiSPUqy9xo0ZGS-RESSD80SJq8.onClick(lambda)
                                                    at android.view.View.performClick(View.java:4438)
                                                    at android.view.View$PerformClick.run(View.java:18422)
                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:136)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                    at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = 3.0.1

Android Version = 4.4.4

Maybe can be solved with reference to this: https://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added

**Comment by anlalalu** [comment]
This defect can be reproduced in latest version.

**Comment by ppareit** [comment]
I would prefer to remove the code that creates an adhoc folder picker. In stead we would use the ACTION_OPEN_DOCUMENT_TREE as we are using this already in the case we are accessing external storage.

**Comment by anlalalu** [comment]
I think that will be a solution.
