### ISSUE TITLE
crash when settting external storage

### ISSUE THREAD

**Issue by anlalalu** [ppareit/swiftp#151]
###### Reproduction Steps

1. tap 'advanced settings'
2. tap 'write external storage'

###### Stack Trace

E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
12-21 22:06:09.720 1667-1667/? E/MessageQueue-JNI: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1541)
                                                       at android.app.Activity.startActivityFromFragment(Activity.java:3957)
                                                       at android.app.Fragment.startActivityForResult(Fragment.java:1079)
                                                       at android.app.Fragment.startActivityForResult(Fragment.java:1063)
                                                       at be.ppareit.swiftp.gui.PreferenceFragment.lambda$onCreate$10(PreferenceFragment.java:241)
                                                       at be.ppareit.swiftp.gui.-$$Lambda$PreferenceFragment$_-VRmfUkU9bu9ld3EYYgExVDVFE.onPreferenceChange(lambda)
                                                       at android.preference.Preference.callChangeListener(Preference.java:897)
                                                       at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:66)
                                                       at android.preference.Preference.performClick(Preference.java:952)
                                                       at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
                                                       at android.widget.AdapterView.performItemClick(AdapterView.java:299)
                                                       at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
                                                       at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
                                                       at android.widget.AbsListView.onTouchUp(AbsListView.java:3657)
                                                       at android.widget.AbsListView.onTouchEvent(AbsListView.java:3436)
                                                       at android.view.View.dispatchTouchEvent(View.java:7706)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
                                                       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
                                                       at android.app.Dialog.dispatchTouchEvent(Dialog.java:746)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
                                                       at android.view.View.dispatchPointerEvent(View.java:7886)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3947)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3826)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3518)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3575)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5532)
                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5512)
                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5483)
                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5612)
                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:138)

###### Debug info
App Version = 2.19

Android Version = 4.4.4

**Comment by anlalalu** [comment]
It seems like the bug has been fixed in latest version.

**Comment by ashutoshgngwr** [comment]
@anlalalu so we can close this then?

**Comment by anlalalu** [comment]
@ashutoshgngwr Yes.
