### ISSUE TITLE
The app throw ActivityNotFoundException when clicking “Market version” button 

### ISSUE THREAD

**Issue by androidAppGuard** [ppareit/swiftp#174]
**the environment is as follows:**
```
App version: v2.19
Android version: 6.0
Device: Nexux_5X
```
**The steps to reproduce:**
![31_swiftp_ActivityNotFoundException.gif](https://s2.loli.net/2022/05/14/mlFEgKc8Ynz3ZxA.gif)
**The exception log is as follows:**
```
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free E/PreferenceFragment: Failed to launch the market.
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=be.ppareit.swiftp flg=0x10000000 }
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1630)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4549)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.app.Activity.startActivityFromFragment(Activity.java:4535)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:6609)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.app.Fragment.startActivity(Fragment.java:1092)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.app.Fragment.startActivity(Fragment.java:1071)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at be.ppareit.swiftp.gui.PreferenceFragment.lambda$onCreate$1(PreferenceFragment.java:105)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at be.ppareit.swiftp.gui.-$$Lambda$PreferenceFragment$cELPp_RVcDXrsUWc0DD6GvxctbQ.onPreferenceClick(lambda)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.preference.Preference.performClick(Preference.java:996)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.widget.AdapterView.performItemClick(AdapterView.java:310)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.widget.AbsListView$3.run(AbsListView.java:3879)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.os.Looper.loop(Looper.java:148)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-14 09:56:33.909 19002-19002/be.ppareit.swiftp_free W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
I don't know why causes it?

**Comment by ppareit** [comment]
Play store not installed?

Should not crash for that, I suppose that is fixed in a recent release.
